using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;


public partial class Employee_Form : System.Web.UI.Page
{
    string str;
    SqlCommand com;
    int count;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            autogenerated();

        }
    }

    void autogenerated()
    {
        SqlConnection con = new SqlConnection("Data Source=WIN-O6R6MCCRT94;Initial Catalog=HousingDb;Integrated Security=True");
        con.Open();

        str = "select count(*) from tbl_Employee";
        com = new SqlCommand(str, con);
        //con.Open();
        count = Convert.ToInt16(com.ExecuteScalar()) + 1;
        txt_id.Text = count.ToString();
        //  txt_id.Enabled = false;
        con.Close();
    }


    protected void btn_save_Click(object sender, EventArgs e)
    {
        SqlConnection con = new SqlConnection("Data Source=WIN-O6R6MCCRT94;Initial Catalog=HousingDb;Integrated Security=True");
        con.Open();
        SqlCommand cmd = new SqlCommand("insert into tbl_Employee values(@emp_id,@emp_name,@emp_desgn,@emp_salary,@emp_mob,@emp_email)", con);
        cmd.Parameters.AddWithValue("@emp_id", Convert.ToInt32(txt_id.Text));
        cmd.Parameters.AddWithValue("@emp_name", txt_name.Text);
        cmd.Parameters.AddWithValue("@emp_desgn", txt_desgn.Text);
        cmd.Parameters.AddWithValue("@emp_salary", Convert.ToInt64(txt_sal.Text));
        cmd.Parameters.AddWithValue("@emp_mob", Convert.ToInt64(txt_mob.Text));
        cmd.Parameters.AddWithValue("@emp_email", txt_email.Text);




        cmd.ExecuteNonQuery();
        con.Close();
        txt_desgn.Text = "";
        txt_id.Text = "";
        txt_name.Text = "";
        txt_email.Text = "";
        txt_mob.Text = "";
        txt_sal.Text = "";
        Label1.Text = "Data Saved Successsfully :-)";

        autogenerated();


        //Response.Redirect("Employee_Form.aspx");


    }
}