
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;

public partial class New_Tenant : System.Web.UI.Page
{
    string str;
    SqlCommand com;
    int count;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            autogenerated();

        }
    }

    void autogenerated()
    {
        SqlConnection con = new SqlConnection("Data Source=ANMOL-PC;Initial Catalog=HousingDb;Integrated Security=True");
        con.Open();

        str = "select count(*) from tbl_Tenant";
        com = new SqlCommand(str, con);
        //con.Open();
        count = Convert.ToInt16(com.ExecuteScalar()) + 1;
        txt_TenantID.Text = count.ToString();
        //  txt_id.Enabled = false;
        con.Close();
    }


    protected void ddOwnerID_SelectedIndexChanged(object sender, EventArgs e)
    {
        SqlConnection con = new SqlConnection("Data Source=ANMOL-PC;Initial Catalog=HousingDb;Integrated Security=True");
        con.Open();
        SqlCommand cmd = new SqlCommand("select FLAT_WING,FLAT_NO,OWNER_NAME,FLAT_SIZE,FLAT_SQFT,FLAT_MAINT,PARKING,OWNERSHIP_DATE FROM tbl_NewOwner where OWNER_ID=@OWNER_ID", con);
        cmd.Connection = con;

        cmd.Parameters.AddWithValue("@OWNER_ID", Convert.ToString(ddOwnerID.SelectedValue));
        SqlDataReader dr = default(SqlDataReader);
        dr = cmd.ExecuteReader();
        dr.Read();
        txt_FlatNo.Text = dr["FLAT_NO"].ToString();
        txt_FlatSize.Text = dr["FLAT_SIZE"].ToString();
        txt_FlatWing.Text = dr["FLAT_WING"].ToString();
        txt_Maint.Text = dr["FLAT_MAINT"].ToString();

        txt_ownerName.Text = dr["OWNER_NAME"].ToString();
        txt_ownerShip.Text = dr["OWNERSHIP_DATE"].ToString();
        txt_Parking.Text = dr["PARKING"].ToString();
        txt_sqFt.Text = dr["FLAT_SQFT"].ToString();

   //     cmd = new SqlCommand("insert into tbl_Maint values(@MAINT_YEAR,@MAINT_MONTH,@OWNER_ID,@FLAT_WING,@FLAT_NO,@OWNER_NAME,@FLAT_SIZE,@FLAT_SQFT,@FLAT_MAINT,@PARKING,@OWNERSHIP_DATE,@OTHER_EXP,@TOTAL)", con);


    }


    protected void btn_save_Click(object sender, ImageClickEventArgs e)
    {

        SqlConnection con = new SqlConnection("Data Source=ANMOL-PC;Initial Catalog=HousingDb;Integrated Security=True");
        con.Open();
        SqlCommand cmd = new SqlCommand("insert into tbl_Tenant values(@TENANT_ID,@TENANT_DATE,@TENANT_NAME,@OWNER_ID,@FLAT_WING,@FLAT_NO,@OWNER_NAME,@FLAT_SIZE,@FLAT_SQFT,@FLAT_MAINT,@PARKING,@OWNERSHIP_DATE)", con);

        cmd.Parameters.AddWithValue("@TENANT_ID", Convert.ToInt32(txt_TenantID.Text)); 
        cmd.Parameters.AddWithValue("@OWNER_ID", Convert.ToInt32(ddOwnerID.SelectedValue));
        cmd.Parameters.AddWithValue("@FLAT_WING", txt_FlatWing.Text);
        cmd.Parameters.AddWithValue("@FLAT_NO", txt_FlatNo.Text);
        cmd.Parameters.AddWithValue("@OWNER_NAME", txt_ownerName.Text);
        cmd.Parameters.AddWithValue("@FLAT_SIZE", txt_FlatSize.Text);
        cmd.Parameters.AddWithValue("@FLAT_SQFT", Convert.ToInt64(txt_sqFt.Text));
        cmd.Parameters.AddWithValue("@FLAT_MAINT", Convert.ToInt64(txt_Maint.Text));
        cmd.Parameters.AddWithValue("@PARKING", txt_Parking.Text);
        cmd.Parameters.AddWithValue("@OWNERSHIP_DATE", txt_ownerShip.Text);
        cmd.Parameters.AddWithValue("@TENANT_NAME", txt_TenantName.Text);
        cmd.Parameters.AddWithValue("@TENANT_DATE", txt_date.Text);
      

        cmd.ExecuteNonQuery();
        con.Close();
        txt_FlatNo.Text = "";
        txt_FlatSize.Text = "";
        txt_FlatWing.Text = "";
        txt_Maint.Text = "";
        txt_ownerName.Text = "";
        txt_ownerShip.Text = "";
        txt_Parking.Text = "";
        txt_sqFt.Text = "";
        txt_date.Text = "";
        txt_TenantName.Text = "";

        autogenerated();
        Label1.Text = "Data Saved..!! :-)";

    }
   
}