using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;

public partial class New_Owner : System.Web.UI.Page
{
    string str;
    SqlCommand com;
    int count;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            autogenerated();
           

        }
    }

    void autogenerated()
    {
        SqlConnection con = new SqlConnection("Data Source=ANMOL-PC;Initial Catalog=HousingDb;Integrated Security=True");
        con.Open();

        str = "select count(*) from tbl_NewOwner";
        com = new SqlCommand(str, con);
        
        count = Convert.ToInt16(com.ExecuteScalar()) + 1;
        txt_ID.Text = count.ToString();
       
        con.Close();
    }

    protected void ddFlatNo_SelectedIndexChanged(object sender, EventArgs e)
    {
        SqlConnection con = new SqlConnection("Data Source=WIN-O6R6MCCRT94;Initial Catalog=HousingDb;Integrated Security=True");
        con.Open();
        SqlCommand cmd = new SqlCommand("select Flat_Size FROM tbl_Flats where Flat_Wing=@Flat_Wing AND Flat_No=@Flat_No", con);
        cmd.Connection = con;

        cmd.Parameters.AddWithValue("@Flat_Wing", Convert.ToString(ddWing.SelectedValue));
        cmd.Parameters.AddWithValue("@Flat_No", Convert.ToString(ddFlatNo.SelectedValue));
        SqlDataReader dr = default(SqlDataReader);
        dr = cmd.ExecuteReader();
        dr.Read();
        txt_FlatSize.Text = dr["Flat_Size"].ToString();
        string flat_size = txt_FlatSize.Text;
        if(flat_size=="1-BHK")
        {
             txt_sqFt.Text="950";
             txt_Maint.Text = "1900";

        }
        else
        {
            txt_sqFt.Text = "1540";
            txt_Maint.Text = "3080";

        }

    }
    protected void btn_Save_Click(object sender, ImageClickEventArgs e)
    {
        SqlConnection con = new SqlConnection("Data Source=WIN-O6R6MCCRT94;Initial Catalog=HousingDb;Integrated Security=True");
        con.Open();
        SqlCommand cmd = new SqlCommand("insert into tbl_NewOwner values(@OWNER_ID,@FLAT_WING,@FLAT_NO,@OWNER_NAME,@FLAT_SIZE,@FLAT_SQFT,@FLAT_MAINT,@PARKING,@OWNERSHIP_DATE)", con);
        cmd.Parameters.AddWithValue("@OWNER_ID", Convert.ToInt32(txt_ID.Text));
        cmd.Parameters.AddWithValue("@FLAT_WING", Convert.ToString(ddWing.SelectedValue));
        cmd.Parameters.AddWithValue("@FLAT_NO", Convert.ToString(ddFlatNo.SelectedValue));
        cmd.Parameters.AddWithValue("@OWNER_NAME", txt_ownerName.Text);
        cmd.Parameters.AddWithValue("@FLAT_SIZE", txt_FlatSize.Text);
        cmd.Parameters.AddWithValue("@FLAT_SQFT", Convert.ToInt64(txt_sqFt.Text));
        cmd.Parameters.AddWithValue("@FLAT_MAINT", Convert.ToInt64(txt_Maint.Text));
        cmd.Parameters.AddWithValue("@PARKING", Convert.ToString(ddParking.SelectedValue));
        cmd.Parameters.AddWithValue("@OWNERSHIP_DATE", txt_ownerShip.Text);


       
        cmd.ExecuteNonQuery();
        //deleting flat 
        cmd = new SqlCommand("delete from tbl_Flats where Flat_Wing=@Flat_Wing and Flat_No=@Flat_No", con);

        cmd.Parameters.AddWithValue("@Flat_Wing", Convert.ToString(ddWing.SelectedValue));
        cmd.Parameters.AddWithValue("@Flat_No", Convert.ToString(ddFlatNo.SelectedValue));
       

        cmd.ExecuteNonQuery();
       // con.Close();
        //username nd pswd
        cmd = new SqlCommand("insert into tbl_OwnerLogin values(@Owner_ID,@Owner_Password,@Owner_Question,@Owner_Answer)", con);

        cmd.Parameters.AddWithValue("@Owner_ID", Convert.ToInt32(txt_ID.Text));
        cmd.Parameters.AddWithValue("@Owner_Password", txt_ownerName.Text);
        cmd.Parameters.AddWithValue("@Owner_Question", Convert.ToString(ddFav.SelectedValue));
        cmd.Parameters.AddWithValue("@Owner_Answer", txt_answer.Text);


        cmd.ExecuteNonQuery();
        con.Close();
      
        txt_answer.Text = "";
        txt_FlatSize.Text = "";
        txt_ID.Text = "";
        txt_Maint.Text = "";
        txt_ownerName.Text = "";
        txt_ownerShip.Text = "";
        txt_sqFt.Text = "";
        Label1.Text = "Data Saved..!!";
       
        autogenerated();

    }
}